### ISSUE TITLE
맺음말 및 글자 수 측정

### ISSUE THREAD

**Issue by tigowler** [Sookpeech/voice_analysis#3]
## 🔥 To-do
- [x] AWS transcribe 결과에 대한 맺음말 분석
- [x] AWS transcribe 결과에 대한 글자 수 분석
- [x] 세 항목에 대한 결과 안내 문구 출력
- [x] transcribe 작업 완료 후 job과 s3 folder 삭제
